source 'https://rubygems.org'
ruby '2.3.1'

gem 'sinatra', :require => 'sinatra/base'
gem 'erubis'
gem 'thin'

gem 'sprockets'
gem 'sprockets-commonjs', '0.0.6'
gem 'uglifier'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'coffee-script'
gem 'stylus'
gem 'stylus-source', '0.31.0'
gem 'eco'
gem 'json', '~> 1.8.3'

gem 'dalli'
gem 'memcachier'
